###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.2"
services:

    redis:
      image: redis:alpine
      container_name: codecourse-redis

    mysql:
      image: mysql:8.0
      container_name: codecourse-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=shop
        - MYSQL_USER=shop
        - MYSQL_PASSWORD=shop
      ports:
        - "9002:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: codecourse-phpmyadmin
      ports:
        - "8080:80"
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
      restart: always
      depends_on:
        - mysql

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: codecourse-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: codecourse-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: codecourse-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

